version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: go-minesweeper-api
    container_name: minesweeper-mvc-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: minesweeper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/minesweeper-mvc
    volumes:
      - minesweeper-mvc:/var/lib/postgresql/data

volumes:
  minesweeper-mvc: